-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,
       SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,
       purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
        SELECT AVG(purchase_amount)
        FROM customer
      );

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
       ROUND(AVG(review_rating::numeric), 2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;

-- Q4. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(
           100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
           / COUNT(*),
       2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Q6. Are repeat buyers also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q7. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,
       ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q8. Segment customers into New, Returning, and Loyal customers.
WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)

SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

-- Q9.Which product categories show the strongest overall performance based on customer purchases?
SELECT category,
       COUNT(customer_id) AS total_purchases
FROM customer
GROUP BY category
ORDER BY total_purchases DESC;

-- Q10. What is the revenue contribution of each age group?
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


-- Q3 Difference

-- PostgreSQL:
-- review_rating::numeric
-- LIMIT 5

-- Oracle:
-- CAST(review_rating AS NUMBER)
-- FETCH FIRST 5 ROWS ONLY


-- Q6 Difference

-- PostgreSQL:
-- LIMIT 5

-- Oracle:
-- FETCH FIRST 5 ROWS ONLY